import os
import json
import time
import re
import argparse
import torch
import pandas as pd
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from PIL import Image

# ─────────────────────────────────────────────
# 1. HARDCODED CONFIGURATION
# ─────────────────────────────────────────────

PICASSO = False  # Flag to use Picasso cluster path

if PICASSO:
    MODEL_ID = "/mnt2/fscratch/users/tic_163_colab/pedrofdez/picasso/prometheus"
    DEFAULT_CACHE_DIR = None
    DEFAULT_INPUT_FILE = r"/mnt2/fscratch/users/tic_163_colab/pedrofdez/picasso/dataset/inferences/shard_57/answers.jsonl"
    DEFAULT_OUTPUT_FILE = r"/mnt2/fscratch/users/tic_163_colab/pedrofdez/picasso/dataset/inferences/shard_57/llm_evaluation_results.jsonl"
else:
    MODEL_ID = "prometheus-eval/prometheus-8x7b-v2.0"
    DEFAULT_CACHE_DIR = r"D:\modelos"
    DEFAULT_INPUT_FILE  = r"D:\inferences\shard_57\MedTrinity25M_full_55k\answers.jsonl"
    DEFAULT_OUTPUT_FILE = r"D:\inferences\shard_57\MedTrinity25M_full_55k\llm_evaluation_results.jsonl"


# ─────────────────────────────────────────────
# 2. RUBRICS
# ─────────────────────────────────────────────

QUESTION_PROMPT="""You are provided with this brain MRI image from a medical dataset.
Your task is to answer the following questions based on the image and green bounding box, and condense your answers into caption-styled text.

###question1
Give me a detailed description of the image, including type of the image, organs in the image, approximate location of these organs and relevant locations of these organs and any medical devices (if present) visible in the image as detailedly as possible.
Note when answering question1:
1. It is irrelevant for this question whether the image depicts a lesion or not. The answer should be the same.
2. Your answer should not contain anything about the green bounding box like the contour itself and its outline.
3. Do not explain or emphasize your analysis.

###question2
Identify and describe any lesions visible in the image, if present. These lesions may be indicated by green bounding boxes; in such cases, prioritize describing the specific regions within these boxes. For each lesion, specify its exact anatomical location and its position relative to reference structures. Describe what is unusual in those regions, providing details on signal intensity, texture, size, and other morphological features.
Note when answering question2:
1. If one or more green bounding boxes are present, they indicate regions of interest; prioritize identifying and describing the pathological findings within every provided bounding box.
2. If no lesion is visible in the image or within the bounding boxes, explicitly state that the image shows no visible lesion.
3. Do not mention the box's physical attributes (e.g., "green line", "contour", or "square outline").
4. Do not use phrase "green bounding box" in your response, use "region of interest" as a substitution.
5. If multiple lesions or bounding boxes exist, ensure each is described individually to maintain a comprehensive clinical description.
6. Do not say anything that is not needed in your analysis, like introduction of the disease and medical equipments.
7. Do not explain or emphasize your analysis.

###question3
Specify the relationship between the identified lesion(s) and other anatomical regions, explaining the underlying cause of this interaction and its clinical probability.
Note when answering question3:
1. Answer this question only if a lesion is present in the image. If no lesion is visible, provide no response for this section.
2. The response must be highly condensed, limited to a maximum of 2 lines.
3. Do not emphasize your analysis.

###Consolidated Clinical Narrative
Synthesize the findings from the three previous questions into a single, fluid paragraph. Avoid a "Question-Answer" format or bullet points. The final output must be a cohesive and slightly condensed descriptive summary that preserves all essential medical details and observations.
"""

RUBRIC_PAIRWISE = f"""
You are an expert neuroradiologist comparing two AI-generated brain MRI reports (Report A and Report B) based on a Reference Ground Truth.

Each response was generated by following the next steps:
1. A pair image-text is passed as argument. The image is a brain mri scan while the text was a prompt which detailed the instructions.
2. Each model (A and B) replies a report.

The question prompt was:
{QUESTION_PROMPT}

Evaluate based on:
- Accuracy of findings
- Correct anatomical localization
- Completeness (no missing findings)
- Appropriate neuroradiology terminology
- Soundness of clinical conclusion
- Prompt alignment

SCORING:
Compare Report A and Report B. Provide a single numerical score between -1.0 and 1.0 representing the relative quality:
- -1.0: Report A is completely better than Report B .
-  0.0: Both reports are of exactly the same quality.
-  1.0: Report B is completely better than Report A .

Use decimal values (e.g., -0.3, 0.05, 0.8) to indicate smaller differences or degrees of preference.

OUTPUT:
You MUST return ONLY the numerical score. No text, no markdown, no reasoning.
Example: 0.75
"""

# ─────────────────────────────────────────────
# 3. PROMETHEUS INFERENCE HELPER
# ─────────────────────────────────────────────

def load_prometheus(model_id, cache_dir=None):
    """
    Loads tokenizer and model. If cache_dir is provided, it downloads/loads 
    the model from that specific location.
    """
    if cache_dir:
        print(f"📂 Storage directory set to: {cache_dir}")
    
    # Load tokenizer and model using the specified cache directory
    tokenizer = AutoTokenizer.from_pretrained(
        model_id, 
        cache_dir=cache_dir
    )
    
    model = AutoModelForCausalLM.from_pretrained(
        model_id, 
        device_map="auto", 
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        cache_dir=cache_dir
    )
    return tokenizer, model



def call_prometheus(tokenizer, model, prompt, max_new_tokens=100):
    """
    Handles local inference using Prometheus chat template.
    """
    messages = [
        {"role": "user", "content": prompt},
    ]
    
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    
    decoded = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return decoded.strip()

def extract_score(text):
    """
    Regex to find the last numerical value in the output.
    """
    if not text: return None
    match = re.findall(r"[-+]?\d*\.?\d+", text)
    if match:
        try:
            val = float(match[-1])
            return max(-1.0, min(1.0, val))
        except: return None
    return None

# ─────────────────────────────────────────────
# 3. EVALUATION FUNCTIONS
# ─────────────────────────────────────────────

def evaluate_pairwise(tokenizer, model, gt, base, ft):
    """
    Performs pairwise evaluation with Prometheus.
    """
    prompt_ab = f"{RUBRIC_PAIRWISE}\n\nREF:\n{gt}\n\nREPORT A:\n{base}\n\nREPORT B:\n{ft}"
    raw_s1 = call_prometheus(tokenizer, model, prompt_ab)
    s1 = extract_score(raw_s1)
    
    prompt_ba = f"{RUBRIC_PAIRWISE}\n\nREF:\n{gt}\n\nREPORT A:\n{ft}\n\nREPORT B:\n{base}"
    raw_s2 = call_prometheus(tokenizer, model, prompt_ba)
    s2 = extract_score(raw_s2)

    if s1 is None or s2 is None:
        return {"score": None, "consistent": False, "raw": [raw_s1, raw_s2]}

    final_score = (s1 - s2) / 2.0
    consistent = (s1 * s2 < 0) or (s1 == 0 and s2 == 0)

    return {
        "score": round(final_score, 4),
        "consistent": consistent
    }

# ─────────────────────────────────────────────
# 4. MAIN PIPELINE
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=DEFAULT_INPUT_FILE)
    parser.add_argument("--output", default=DEFAULT_OUTPUT_FILE)
    parser.add_argument("--cache_dir", default=DEFAULT_CACHE_DIR, help="Path to your external hard drive folder")
    args = parser.parse_args()

    # The model will download to args.cache_dir if it's not already there
    print(f"📦 Initializing {MODEL_ID}...")
    tokenizer, model = load_prometheus(MODEL_ID, cache_dir=args.cache_dir)

    input_path = Path(args.input)
    output_path = Path(args.output)

    with open(input_path, "r", encoding="utf-8") as f:
        cases = [json.loads(line) for line in f]

    print(f"🚀 Evaluating {len(cases)} cases...")
    
    # Initialize statistics
    stats = {
        "count": 0,
        "score_sum": 0.0,
        "consistent_count": 0
    }

    with open(output_path, "a", encoding="utf-8") as f_out:
        pbar = tqdm(cases, desc="Evaluating (Pairwise)")
        for case in pbar:
            gt = case.get("caption") or ""
            base_r = case.get("model_base_response") or ""
            ft_r = case.get("model_ft_response") or ""

            eval_res = evaluate_pairwise(tokenizer, model, gt, base_r, ft_r)

            # Update statistics
            stats["count"] += 1
            if eval_res["score"] is not None:
                stats["score_sum"] += eval_res["score"]
            if eval_res.get("consistent"):
                stats["consistent_count"] += 1

            # Update progress bar
            avg_score = stats["score_sum"] / stats["count"]
            consistency = (stats["consistent_count"] / stats["count"]) * 100
            
            pbar.set_postfix({
                "avg_score": f"{avg_score:.3f}",
                "consistency": f"{consistency:.1f}%"
            })

            res = {
                "case_id": case.get("file_name"),
                "pairwise": eval_res
            }

            json.dump(res, f_out, ensure_ascii=False)
            f_out.write("\n")
            f_out.flush()

if __name__ == "__main__":
    main()